name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Berjalan otomatis setiap jam 12 malam

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update file
        run: |
          date > activity.txt

      - name: Commit and Push
        run: |
          git config --global user.name "Nama GitHub Anda"
          git config --global user.email "email@anda.com"
          git add activity.txt
          git commit -m "Daily update: $(date)"
          git push
